var bookOfAnswersArray = [
  "Yes, definitely.",
  "Outlook good.",
  "My sources say no.",
  "Very doubtful.",
  "Cannot predict now.",
  "You may rely on it.",
  "As I see it, yes.",
  "Most likely.",
  "Yes.",
  "Concentrate and ask again.",
  "Don't count on it.",
  "Reply hazy, try again.",
  "Better not tell you now.",
  "Ask again later.",
  "Signs point to yes.",
  "Absolutely not.",
  "Outlook not so good.",
  "Without a doubt.",
  "Definitely not.",
  "It is decidedly so.",
  "Very likely.",
  "The answer is within you.",
  "The outlook is positive.",
  "All signs point to yes.",
  "The future is hazy.",
  "It is not certain.",
  "It is beyond my power to answer that.",
  "The outlook is cloudy.",
  "The answer is no, but it may change.",
  "The answer is likely yes.",
  "The odds are not in your favor.",
  "The outcome looks good.",
  "Not a chance.",
  "It is possible.",
  "The answer is a resounding yes.",
  "It is better left unknown.",
  "Do not count on it.",
  "There is a good chance.",
  "I'm sorry, I do not know the answer.",
  "The outcome is uncertain.",
  "It is highly unlikely.",
  "The answer is probably not.",
  "It is possible, but not certain.",
  "Absolutely maybe.",
  "Signs are unclear, ask again.",
  "Chances are high.",
  "The answer lies within your heart.",
  "Signs are pointing in your favor.",
  "It is a definite maybe.",
  "The outlook is unclear.",
  "I'm sorry, I cannot answer that now.",
  "It is not clear at this time.",
  "Ask someone else.",
  "Maybe.",
  "The answer is probably yes.",
  "Signs are pointing towards no.",
  "I do not have enough information to answer.",
  "The outlook is good.",
  "It is highly probable.",
  "The outcome is favorable.",
  "It is not looking good.",
  "It is likely.",
  "The outlook is not good.",
  "It is not advisable.",
  "I'm sorry, I cannot answer that at this time.",
  "Absolutely positively.",
  "It is doubtful.",
  "Signs point to no.",
  "The answer is uncertain.",
  "The future is uncertain.",
  "The answer is no, and will not change.",
  "The outcome is negative.",
  "It is not worth pursuing.",
  "The chances are slim.",
  "The answer is hidden.",
  "The answer is right in front of you.",
  "It is not a good time.",
  "You already know the answer.",
  "The future looks bright.",
  "It is worth the effort.",
  "It is not meant to be.",
  "The answer is not what you want to hear.",
  "The path ahead is uncertain.",
  "The answer is not clear.",
  "The outcome is unlikely.",
  "It is better to wait.",
  "The answer is yes, but with conditions.",
  "The answer is no, but with conditions.",
  "It is not the right time.",
  "The answer is within reach.",
  "The answer is complicated.",
  "It is possible, but difficult.",
  "The answer is in the details.",
  "It is not as simple as it seems.",
  "No.",
];

export default bookOfAnswersArray;
